### ISSUE TITLE
.yaml 

### ISSUE THREAD

**Issue by direx1** [shlomki/HomeAssistant-Config#1]
Hi, great work on this. Does this code need breaking down into relevant folders or can I paste directly into configuration.yaml? Perhaps even into its own file with  !include filename.yaml

**Comment by shlomki** [comment]
Hi, the code doesn't need to be broken down, it's a package.
You can read about it here:
https://www.home-assistant.io/docs/configuration/packages/

There's also an example in my configuration.yaml file.
