### ISSUE TITLE
shelly_3em.yaml

### ISSUE THREAD

**Issue by danielk39** [shlomki/HomeAssistant-Config#2]
בוקר טוב, ניסיתי להגדיר אצלי כמו שהסברת כאן וחסר לי נתונים , חשבון קודם לא מתעדכן לי,תשלום עתידי גם לא,
אשמח אם תוכל לעזור לי.
  sensors:
      power_total:
        friendly_name: "Total Power"
        unit_of_measurement: 'watt'
        value_template: "{{ (states('sensor.shelly_em_50a_channel_1_power') | float) | round(2)}}"
      energy_total:
        friendly_name: "Total Energy"
        unit_of_measurement: 'kWh'
        value_template: "{{ states('sensor.shelly_em_50a_channel_1_energy') | float}}"
      energy_total_today:
        friendly_name: "Total Energy Today"
        value_template: "{{ (states('sensor.energy_total') | float) - (states('input_text.energy_total_yesterday') | float) }}"
        unit_of_measurement: "kWh"
      power_cost_per_hour:
        friendly_name: "Cost per Hour"
        unit_of_measurement: 'NIS'
        value_template: "{{ (states('sensor.power_total') | float / 1000 * states('input_text.power_nis_per_kwh') | float)|round(2) }}"
      power_nis_per_kwh:
        friendly_name: Power NIS per kWh (incl. VAT)
        value_template: "{{ states('input_text.power_nis_per_kwh') | float }}"
        unit_of_measurement: "NIS"
      energy_total_today_cost:
        friendly_name: "Today Cost"
        value_template: "{{ ((states('sensor.energy_total_today') | float) * (states('input_text.power_nis_per_kwh') | float))|round(1) }}"
        unit_of_measurement: "NIS"
      energy_total_next_bill_cost:
        friendly_name: "Next Bill Cost"
        value_template: "{{ ((states('sensor.energy_total_next_bill') | float) * (states('input_text.power_nis_per_kwh') | float) + (states('input_text.power_monthly_additional_cost') | int ))|round(1)}}"
        unit_of_measurement: "NIS"

**Comment by shlomki** [comment]
היי, הסנסורים האלה לא יודעים לחשב בדיעבד מה היה החשבון הקודם ולכן גם לא יודעים מה יהיה החשבון הבא שלך עד שהוא יתאפס. 
ברגע שהחשבון שלך יתאפס, הסנסורים של החשבון הקודם והחשבון הבא יתחילו לעבוד.
אתה יכול להגדיר כבדיקה שהוא יתאפס היום בלילה, ואז אתה אמור להתחיל לראות שהם עובדים. כמובן שהמידע לא יהיה נכון כי אתה מאפס באמצע החודש, אבל ככה תדע שהכל עובד נכון.

**Comment by danielk39** [comment]
ואיך בעצם אני עושה את הבדיקה? אני דיי חדש בHA, ואין לי ידע בתכנות.

**Comment by shlomki** [comment]
כמו שרשום בהערות בתחילת הקובץ.
input_select.power_bill_cutoff_month:
פה אתה מגדיר באיזה חודשים יחתך החשבון. כיוון שאנחנו בפברואר אז אתה צריך לבחור חודשים זוגיים , כלומר Even.

input_number.power_bill_cutoff_day:
פה אתה מגדיר באיזה יום בחודש אתה רוצה שיחתך החשבון. למשל אם אתה רוצה שיחתך ב-26 לחודש, אז פשוט מגדירים שם 26.

**Comment by danielk39** [comment]
![Screenshot_20220226-101605_Home Assistant](https://user-images.githubusercontent.com/92187807/155835846-4eb79404-0ecb-46aa-bfaf-4f9ea52512f3.jpg)
עשיתי כמו שאמרת ובכל זאת לא משתנה לי 🤷

**Comment by shlomki** [comment]
אני רואה שחשבון עתידי כן מתעדכן לך וגם תשלום יומי, זה אומר שהכל נראה ומוגדר בסדר.
מעבר לכך אם החשבון לא נחתך לפי מה שהגדרת אז אתה צריך לבדוק את האוטומציה שיש בקוד, אולי שינית משהו שגרם לה לא לרוץ?

**Comment by danielk39** [comment]
לא, האוטומציה רצה כל לילה🤷
אז אני לא מבין למה חשבון קודם לא מתעדכן. בדקתי את עצמי כמה וכמה פעמים לפי
מה שאני שמופיע כאן( העתקתי אחד לאחד)

בתאריך שבת, 26 בפבר׳ 2022, 21:04, מאת shlomki ***@***.***>:

**Comment by shlomki** [comment]
שינית את שינית את השורה של notify.bffs?
כי אחרת בטח האוטומציה קורסת לך באמצע.
אם כן, שלח צילום מסך של כל הסנסורים ממסך ה dev tools (לא מה ui שלך)

**Comment by danielk39** [comment]
> שינית את שינית את השורה של notify.bffs?
> כי אחרת בטח האוטומציה קורסת לך באמצע.
> אם כן, שלח צילום מסך של כל הסנסורים ממסך ה dev tools (לא מה ui שלך)

כן בוודאי כרגע אני משתמש בשרות של ha ומקבל התראה בטלפון.

איך אני שולח /מגיע לזה? אני קצת חדש בתחום.

**Comment by danielk39** [comment]
![Screenshot_20220226-230951_Home Assistant.jpg](https://user-images.githubusercontent.com/92187807/155859145-ce16d2f3-3001-4ca8-8a92-71bff48aa35f.jpg) זה מה שרצית?

**Comment by shlomki** [comment]
כן, אבל תפלטר למעלה לפי
sensor.power
ו-
sensor.energy

**Comment by danielk39** [comment]
![Screenshot_20220226-232913_Home Assistant.jpg](https://user-images.githubusercontent.com/92187807/155859727-dfbb7d9e-6305-45f7-ad43-d8eda3949ecf.jpg)

**Comment by danielk39** [comment]
השאלה למה יוצא לי ככה?

**Comment by shlomki** [comment]
נראה שיוצא לך בסדר אבל קשה לי לבדוק ככה לעומק, שלח לי הודעה בפייסבוק וננסה לפתור אונליין. אהיה פנוי בשעות הערב
http://fb.me/shlomki
